development:
  adapter: mysql2
  database: bloggie_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  database: bloggie_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  database: bloggie
  username: root
  password:
  host: localhost
