# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 207dd64ad764ad3a3cde4bbaf2b9d6f0784f9967602e693ce0965f303159dadc3a5ebb91a4c953942f93bfd6339e0acf0bc432c3c09194ed748b9ab9e9381cba

test:
  secret_key_base: 324e41b02455d61b2a0631a5adf7669a3ebab287aed12a247b08530bd9b5a2a92abdbcd8a86edf8316e5345eedb8654dd67c486f416db3a06db3ddf2e5c69773

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
